// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrinzpzqzcvlpastuyjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyaW56cHpxemN2bHBhc3R1eWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTYzODIsImV4cCI6MjA3MDA3MjM4Mn0.Rvsbyme84ZqdRR1mU8EPcPfyuMXq5QZ9NaSLo1ouzqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});